trigger:
- master
- develop

pool:
  vmImage: 'windows-2022'

steps:

- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: VSBuild@1
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    vsVersion: '17.0'
    msbuildArgs: '/p:GitBranch=$(Build.SourceBranchName)'
    configuration: '$(BuildConfiguration)'
    clean: true

#- script: dotnet nuget push *.nupkg --api-key $(NuGetApiKey) --source $(NuGetSource)
#  workingDirectory: src/DialogMessaging/bin/$(BuildConfiguration)
#  displayName: Push DialogMessaging

#- script: dotnet nuget push *.nupkg --api-key $(NuGetApiKey) --source $(NuGetSource)
#  workingDirectory: src/DialogMessaging.MvvmCross/bin/$(BuildConfiguration)
#  displayName: Push DialogMessaging.MvvmCross