trigger:
- master
- develop

pool:
  vmImage: 'macos-latest'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '/src/DialogMessaging/DialogMessaging.csproj;/src/DialogMessaging.MvvmCross/DialogMessaging.MvvmCross.csproj'
    versioningScheme: 'off'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '12a53b34-f558-4977-8856-90084888c990'