trigger:
- master
- develop

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '\src\DialogMessaging\DialogMessaging.csproj;\src\DialogMessaging.MvvmCross\DialogMessaging.MvvmCross.csproj'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '\src\DialogMessaging\bin\$(buildConfiguration)\*.nupkg;\src\DialogMessaging.MvvmCross\bin\$(buildConfiguration)\*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '12a53b34-f558-4977-8856-90084888c990'