version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: Build Solution
          command: dotnet build -c Release
      - run:
          name: Push DialogMessaging to NuGet
          command: dotnet nuget push *.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE
          working_directory: src/DialogMessaging/bin/Release
      - run:
          name: Push DialogMessaging.MvvmCross to NuGet
          command: dotnet nuget push *.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE
          working_directory: src/DialogMessaging.MvvmCross/bin/Release

workflows:
  version: 2
  main:
    jobs:
      - build:
          context:
            - NuGet
          filters:
            branches:
              only:
                - master
                - develop